services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    gpus: all
    volumes:
      - ollama_data:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "4000:8080"
    restart: unless-stopped
    depends_on:
      - ollama
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    volumes:
      - openwebui_data:/app/backend/data

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    entrypoint: >
      sh -c "
      until curl -sf http://ollama:11434/api/tags >/dev/null; do sleep 1; done;
      ollama pull gpt-oss:20b
      "
    restart: "no"


volumes:
  ollama_data:
  openwebui_data:
